import { EditorView } from "@codemirror/view";

// Theme for AI features
export const aiTheme = EditorView.baseTheme({
  ".cm-ai-input-container": {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "min(calc(100% + 7px), 500px)",
    padding: "8px",
    margin: "0 -6px",
    backgroundColor: "var(--background-higher, var(--cm-background))",
    color: "var(--foreground, var(--cm-foreground))",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))"
  },
  ".cm-ai-input": {
    display: "block",
    width: "100%",
    padding: "6px 10px",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
    borderRadius: "6px",
    fontSize: "13px",
    backgroundColor: "var(--background, var(--cm-background))",
    color: "var(--foreground, var(--cm-foreground))",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    "&:focus": {
      outline: "none",
      borderColor: "var(--accent-primary, var(--cm-accent))",
      boxShadow: "0 0 0 2px color-mix(in srgb, var(--accent-primary, var(--cm-accent)) 20%, transparent)",
    },
    "&::placeholder": {
      color: "var(--foreground-muted, var(--cm-foreground-muted))",
    },
  },
  ".cm-ai-help-info-button": {
    fontSize: "11px",
    padding: "4px 8px",
    height: "24px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    display: "inline-flex",
    alignItems: "center",
    marginRight: "auto",
    borderRadius: "2px",
    transition: "all 0.2s ease",
    border: "none",
    background: "transparent",
    "&:hover": {
      color: "var(--foreground, var(--cm-foreground))",
      background: "var(--background-higher, rgba(255, 255, 255, 0.05))",
    },
  },
  ".cm-ai-generate-button": {
    background: "var(--accent-primary, var(--cm-accent))",
    border: "none",
    padding: "6px 14px",
    color: "var(--foreground-on-accent, #ffffff)",
    cursor: "pointer",
    font: "inherit",
    fontSize: "12px",
    fontWeight: "600",
    borderRadius: "2px",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    transition: "all 0.2s ease",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.1)",
    "&:hover": {
      filter: "brightness(110%)",
      transform: "translateY(-1px)",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.15)",
    },
    "&:active": {
      transform: "translateY(0)",
      filter: "brightness(95%)",
      boxShadow: "0 1px 2px rgba(0, 0, 0, 0.1)",
    },
    "&:disabled": {
      opacity: "0.6",
      cursor: "not-allowed",
      transform: "none",
      filter: "none",
    },
  },
  ".cm-ai-cancel-button": {
    padding: "6px 12px",
    fontSize: "11px",
    borderRadius: "2px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    cursor: "pointer",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
    background: "var(--background, var(--cm-background))",
    transition: "all 0.2s ease",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    fontWeight: "500",
    "&:hover": {
      color: "var(--error, var(--cm-error))",
      background: "color-mix(in srgb, var(--error, var(--cm-error)) 8%, transparent)",
      borderColor: "var(--error, var(--cm-error))",
    },
    "&:active": {
      transform: "translateY(1px)",
    },
  },
  ".cm-line.cm-ai-selection, .cm-line.cm-ai-selection.cm-active-line": {
    backgroundColor: "var(--background-higher, color-mix(in srgb, var(--cm-selection) 30%, transparent)) !important",
    padding: "0 4px",
    overflow: "hidden",
  },
  ".cm-line:has(.cm-new-code-line)": {
    backgroundColor: "color-mix(in srgb, var(--cm-success) 15%, var(--background, var(--cm-background))) !important",
    position: "relative",
    padding: "2px 4px",
   
  },
  ".cm-new-code-line": {
    position: "relative",
    display: "inline-block",
    width: "100%",
    color: "var(--success-foreground, var(--cm-success-foreground, var(--foreground)))",
   
  },
  ".cm-old-code-container": {
    backgroundColor: "color-mix(in srgb, var(--cm-error) 15%, var(--background, var(--cm-background)))",
    position: "relative",
    display: "flex",
    padding: "8px 12px",
    width: "100%",
    alignItems: "center",
    margin: "4px 0",
    color: "var(--error-foreground, var(--cm-error-foreground, var(--foreground)))",

  },
  ".cm-old-code": {
    fontFamily: "inherit",
    fontSize: "inherit",
    color: "var(--foreground, var(--cm-foreground))",
    padding: "2px 0",
    display: "inline-block",
    width: "100%",
    opacity: "0.9",
  },
  ".cm-diff-highlight-add": {
    backgroundColor: "color-mix(in srgb, var(--cm-success) 25%, transparent)",
    borderRadius: "3px",
    margin: "0 -2px",
    padding: "2px 4px",
    position: "relative",
    color: "var(--success-foreground, var(--cm-success-foreground, var(--foreground)))",
    "&::before": {
      content: '""',
      position: "absolute",
      left: "-2px",
      top: "0",
      bottom: "0",
      width: "2px",
      backgroundColor: "var(--cm-success)",
      borderTopLeftRadius: "3px",
      borderBottomLeftRadius: "3px",
    },
  },
  ".cm-diff-highlight-remove": {
    backgroundColor: "color-mix(in srgb, var(--cm-error) 25%, transparent)",
    borderRadius: "3px",
    margin: "0 -2px",
    padding: "2px 4px",
    position: "relative",
    color: "var(--error-foreground, var(--cm-error-foreground, var(--foreground)))",
    "&::before": {
      content: '""',
      position: "absolute",
      left: "-2px",
      top: "0",
      bottom: "0",
      width: "2px",
      backgroundColor: "var(--cm-error)",
      borderTopLeftRadius: "3px",
      borderBottomLeftRadius: "3px",
    },
  },
  ".cm-code-button": {
    position: "absolute",
    right: "5px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "var(--background-higher, rgba(255, 255, 255, 0.05))",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
    padding: "3px 8px",
    cursor: "pointer",
    fontSize: "12px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    borderRadius: "2px",
    transition: "all 0.2s ease",
    "&:hover": {
      color: "var(--foreground, var(--cm-foreground))",
      background: "var(--background-highest, rgba(255, 255, 255, 0.1))",
      borderColor: "var(--border-hover, rgba(255, 255, 255, 0.2))",
    },
    "&:active": {
      transform: "translateY(-50%) scale(0.98)",
    },
  },
  ".cm-floating-buttons": {
    fontFamily: "var(--font-ui, system-ui, -apple-system, sans-serif)",
    position: "absolute",
    top: "-28px",
    left: "5px",
    display: "flex",
    gap: "1px",
    borderRadius: "2px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.2)",
  },
  ".cm-floating-button": {
    fontFamily: "inherit",
    padding: "4px 10px",
    fontSize: "11px",
    cursor: "pointer",
    fontWeight: "500",
    border: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s ease",
  },
  ".cm-floating-accept": {
    backgroundColor: "var(--success, var(--cm-success))",
    color: "var(--foreground-on-success, #ffffff)",
    "&:hover": {
      filter: "brightness(110%)"
    }
  },
  ".cm-floating-reject": {
    backgroundColor: "var(--error, var(--cm-error))",
    color: "var(--foreground-on-error, #ffffff)",
    "&:hover": {
      filter: "brightness(110%)"
    }
  },
  ".cm-ai-loading-indicator": {
    fontStyle: "italic",
    fontSize: "11px",
    paddingLeft: "12px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    opacity: "0",
    transition: "opacity 0.3s ease-in-out",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    "&::after": {
      content: '""',
      display: "inline-block",
      width: "12px",
      height: "12px",
      border: "2px solid var(--accent-primary, var(--cm-accent))",
      borderTopColor: "transparent",
      borderRadius: "50%",
      animation: "spin 1s linear infinite",
    },
    "&:not(:empty)": {
      opacity: "1",
    },
  },
  "@keyframes spin": {
    "0%": { transform: "rotate(0deg)" },
    "100%": { transform: "rotate(360deg)" },
  },
  ".cm-old": {
    backgroundColor: "rgba(244, 67, 54, 0.15)"
  },
  ".cm-new": {
    backgroundColor: "rgba(76, 175, 80, 0.15)"
  },
}); 