import { EditorView } from "@codemirror/view";

// Theme for AI features
export const aiTheme = EditorView.baseTheme({
  ".cm-ai-input-container": {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    width: "min(calc(100% + 7px), 500px)",
    padding: "8px",
    margin: "0 -6px",
    backgroundColor: "var(--background-higher, var(--cm-background))",
    color: "var(--foreground, var(--cm-foreground))",
    borderRadius: "8px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.15)",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
  },
  ".cm-ai-input": {
    display: "block",
    width: "100%",
    padding: "6px 10px",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
    borderRadius: "6px",
    fontSize: "13px",
    backgroundColor: "var(--background, var(--cm-background))",
    color: "var(--foreground, var(--cm-foreground))",
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    "&:focus": {
      outline: "none",
      borderColor: "var(--accent-primary, var(--cm-accent))",
      boxShadow: "0 0 0 2px color-mix(in srgb, var(--accent-primary, var(--cm-accent)) 20%, transparent)",
    },
    "&::placeholder": {
      color: "var(--foreground-muted, var(--cm-foreground-muted))",
    },
  },
  ".cm-ai-help-info-button": {
    fontSize: "11px",
    padding: "4px 8px",
    height: "24px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    display: "inline-flex",
    alignItems: "center",
    marginRight: "auto",
    borderRadius: "4px",
    transition: "all 0.2s ease",
    border: "none",
    background: "transparent",
    "&:hover": {
      color: "var(--foreground, var(--cm-foreground))",
      background: "var(--background-higher, rgba(255, 255, 255, 0.05))",
    },
  },
  ".cm-ai-generate-button": {
    background: "var(--accent-primary, var(--cm-accent))",
    border: "none",
    padding: "4px 12px",
    color: "var(--foreground-on-accent, #ffffff)",
    cursor: "pointer",
    font: "inherit",
    fontSize: "12px",
    fontWeight: "500",
    borderRadius: "4px",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s ease",
    "&:hover": {
      filter: "brightness(110%)",
      transform: "translateY(-1px)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  ".cm-line.cm-ai-selection, .cm-line.cm-ai-selection.cm-active-line": {
    backgroundColor: "var(--selection-background, color-mix(in srgb, var(--cm-selection) 30%, transparent)) !important",
  },
  ".cm-line:has(.cm-new-code-line)": {
    backgroundColor: "var(--success-background, color-mix(in srgb, var(--cm-success) 30%, transparent)) !important",
    position: "relative",
    "&::before": {
      content: '""',
      position: "absolute",
      left: "-20px",
      width: "3px",
      height: "100%",
      backgroundColor: "var(--success, var(--cm-success))",
    },
  },
  ".cm-new-code-line": {
    position: "relative",
    backgroundColor: "var(--success-background, color-mix(in srgb, var(--cm-success) 45%, transparent))",
    display: "inline-block",
    width: "100%",
    color: "var(--success-foreground, var(--cm-success-foreground, var(--foreground)))",
    "&::before": {
      content: '"+"',
      color: "var(--success, var(--cm-success))",
      marginRight: "8px",
      fontWeight: "bold",
      display: "inline-block",
    },
  },
  ".cm-old-code-container": {
    backgroundColor: "var(--error-background, color-mix(in srgb, var(--cm-error) 30%, transparent))",
    position: "relative",
    display: "flex",
    padding: "8px 12px",
    width: "100%",
    alignItems: "center",
    borderRadius: "6px",
    margin: "4px 0",
    border: "1px solid var(--error, color-mix(in srgb, var(--cm-error) 40%, transparent))",
    color: "var(--error-foreground, var(--cm-error-foreground, var(--foreground)))",
    "&::before": {
      content: '""',
      position: "absolute",
      left: "0",
      width: "3px",
      height: "100%",
      backgroundColor: "var(--error, var(--cm-error))",
      borderTopLeftRadius: "6px",
      borderBottomLeftRadius: "6px",
    },
  },
  ".cm-old-code": {
    fontFamily: "inherit",
    fontSize: "inherit",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    textDecoration: "line-through",
    opacity: "0.8",
    padding: "2px 0",
    backgroundColor: "var(--error-background, color-mix(in srgb, var(--cm-error) 25%, transparent))",
    display: "inline-block",
    width: "100%",
    "&::before": {
      content: '"−"',
      color: "var(--error, var(--cm-error))",
      marginRight: "8px",
      fontWeight: "bold",
    },
  },
  ".cm-diff-highlight-add": {
    backgroundColor: "var(--success-background-strong, color-mix(in srgb, var(--cm-success) 50%, transparent))",
    borderRadius: "2px",
    margin: "0 -2px",
    padding: "0 2px",
  },
  ".cm-diff-highlight-remove": {
    backgroundColor: "var(--error-background-strong, color-mix(in srgb, var(--cm-error) 40%, transparent))",
    borderRadius: "2px",
    margin: "0 -2px",
    padding: "0 2px",
  },
  ".cm-code-button": {
    position: "absolute",
    right: "5px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "var(--background-higher, rgba(255, 255, 255, 0.05))",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
    padding: "3px 8px",
    cursor: "pointer",
    fontSize: "12px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    borderRadius: "4px",
    transition: "all 0.2s ease",
    "&:hover": {
      color: "var(--foreground, var(--cm-foreground))",
      background: "var(--background-highest, rgba(255, 255, 255, 0.1))",
      borderColor: "var(--border-hover, rgba(255, 255, 255, 0.2))",
    },
    "&:active": {
      transform: "translateY(-50%) scale(0.98)",
    },
  },
  ".cm-floating-buttons": {
    fontFamily: "var(--font-ui, system-ui, -apple-system, sans-serif)",
    position: "absolute",
    top: "-28px",
    left: "5px",
    display: "flex",
    gap: "1px",
    borderRadius: "6px",
    overflow: "hidden",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.2)",
  },
  ".cm-floating-button": {
    fontFamily: "inherit",
    padding: "4px 10px",
    fontSize: "11px",
    cursor: "pointer",
    fontWeight: "500",
    border: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
    transition: "all 0.2s ease",
  },
  ".cm-floating-accept": {
    backgroundColor: "var(--success, var(--cm-success))",
    color: "var(--foreground-on-success, white)",
    "&:hover": {
      filter: "brightness(110%)",
    },
    "&:active": {
      filter: "brightness(90%)",
    },
  },
  ".cm-floating-reject": {
    backgroundColor: "var(--error, var(--cm-error))",
    color: "var(--foreground-on-error, white)",
    "&:hover": {
      filter: "brightness(110%)",
    },
    "&:active": {
      filter: "brightness(90%)",
    },
  },
  ".hotkey": {
    display: "inline-flex",
    alignItems: "center",
    padding: "1px 4px",
    borderRadius: "3px",
    backgroundColor: "color-mix(in srgb, currentColor 15%, transparent)",
    fontSize: "90%",
    fontWeight: "normal",
    letterSpacing: "0.02em",
  },
  ".cm-ai-loading-indicator": {
    fontStyle: "italic",
    fontSize: "11px",
    paddingLeft: "12px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    opacity: "0",
    transition: "opacity 0.3s ease-in-out",
    "&::after": {
      content: '""',
      display: "inline-block",
      animation: "ellipsis-pulse 1.5s steps(4, end) infinite",
    },
    "&:not(:empty)": {
      opacity: "1",
    },
  },
  ".cm-ai-input:disabled": {
    opacity: "0.6",
    cursor: "not-allowed",
  },
  "@keyframes ellipsis-pulse": {
    "0%": { content: "'.'", },
    "25%": { content: "'..'", },
    "50%": { content: "'...'", },
    "75%": { content: "''" },
  },
  ".cm-ai-loading-container": {
    display: "flex",
    alignItems: "center",
    padding: "4px 8px",
    gap: "8px",
    background: "var(--background, var(--cm-background))",
    borderRadius: "6px",
  },
  ".cm-ai-cancel-button": {
    padding: "3px 8px",
    fontSize: "11px",
    borderRadius: "4px",
    color: "var(--foreground-muted, var(--cm-foreground-muted))",
    cursor: "pointer",
    border: "1px solid var(--border, rgba(255, 255, 255, 0.1))",
    background: "transparent",
    transition: "all 0.2s ease",
    "&:hover": {
      color: "var(--foreground, var(--cm-foreground))",
      background: "var(--background-higher, rgba(255, 255, 255, 0.05))",
      borderColor: "var(--border-hover, rgba(255, 255, 255, 0.2))",
    },
    "&:active": {
      transform: "translateY(1px)",
    },
  },
  ".hidden": {
    display: "none",
  },
});
